// flow-typed signature: 2912d6acedd1d40518b4412aaa36496a
// flow-typed version: <<STUB>>/shades_v^1.8.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shades'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shades' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'shades/lib/compiler/compile' {
  declare module.exports: any;
}

declare module 'shades/lib/compiler/parser' {
  declare module.exports: any;
}

declare module 'shades/lib/index' {
  declare module.exports: any;
}

declare module 'shades/lib/lens-consumers/compose' {
  declare module.exports: any;
}

declare module 'shades/lib/lens-consumers/getters' {
  declare module.exports: any;
}

declare module 'shades/lib/lens-consumers/setters' {
  declare module.exports: any;
}

declare module 'shades/lib/lens-crafters/attr' {
  declare module.exports: any;
}

declare module 'shades/lib/lens-crafters/ix' {
  declare module.exports: any;
}

declare module 'shades/lib/lens-crafters/lens' {
  declare module.exports: any;
}

declare module 'shades/lib/traversals/all' {
  declare module.exports: any;
}

declare module 'shades/lib/traversals/matching' {
  declare module.exports: any;
}

declare module 'shades/lib/traversals/unless' {
  declare module.exports: any;
}

declare module 'shades/lib/utils/function/index' {
  declare module.exports: any;
}

declare module 'shades/lib/utils/index' {
  declare module.exports: any;
}

declare module 'shades/lib/utils/list/index' {
  declare module.exports: any;
}

declare module 'shades/lib/utils/logical/index' {
  declare module.exports: any;
}

declare module 'shades/lib/utils/math/index' {
  declare module.exports: any;
}

declare module 'shades/lib/utils/updateAll' {
  declare module.exports: any;
}

declare module 'shades/lib/utils/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'shades/lib/compiler/compile.js' {
  declare module.exports: $Exports<'shades/lib/compiler/compile'>;
}
declare module 'shades/lib/compiler/parser.js' {
  declare module.exports: $Exports<'shades/lib/compiler/parser'>;
}
declare module 'shades/lib/index.js' {
  declare module.exports: $Exports<'shades/lib/index'>;
}
declare module 'shades/lib/lens-consumers/compose.js' {
  declare module.exports: $Exports<'shades/lib/lens-consumers/compose'>;
}
declare module 'shades/lib/lens-consumers/getters.js' {
  declare module.exports: $Exports<'shades/lib/lens-consumers/getters'>;
}
declare module 'shades/lib/lens-consumers/setters.js' {
  declare module.exports: $Exports<'shades/lib/lens-consumers/setters'>;
}
declare module 'shades/lib/lens-crafters/attr.js' {
  declare module.exports: $Exports<'shades/lib/lens-crafters/attr'>;
}
declare module 'shades/lib/lens-crafters/ix.js' {
  declare module.exports: $Exports<'shades/lib/lens-crafters/ix'>;
}
declare module 'shades/lib/lens-crafters/lens.js' {
  declare module.exports: $Exports<'shades/lib/lens-crafters/lens'>;
}
declare module 'shades/lib/traversals/all.js' {
  declare module.exports: $Exports<'shades/lib/traversals/all'>;
}
declare module 'shades/lib/traversals/matching.js' {
  declare module.exports: $Exports<'shades/lib/traversals/matching'>;
}
declare module 'shades/lib/traversals/unless.js' {
  declare module.exports: $Exports<'shades/lib/traversals/unless'>;
}
declare module 'shades/lib/utils/function/index.js' {
  declare module.exports: $Exports<'shades/lib/utils/function/index'>;
}
declare module 'shades/lib/utils/index.js' {
  declare module.exports: $Exports<'shades/lib/utils/index'>;
}
declare module 'shades/lib/utils/list/index.js' {
  declare module.exports: $Exports<'shades/lib/utils/list/index'>;
}
declare module 'shades/lib/utils/logical/index.js' {
  declare module.exports: $Exports<'shades/lib/utils/logical/index'>;
}
declare module 'shades/lib/utils/math/index.js' {
  declare module.exports: $Exports<'shades/lib/utils/math/index'>;
}
declare module 'shades/lib/utils/updateAll.js' {
  declare module.exports: $Exports<'shades/lib/utils/updateAll'>;
}
declare module 'shades/lib/utils/utils.js' {
  declare module.exports: $Exports<'shades/lib/utils/utils'>;
}
